"""Add display_name to questions

Revision ID: 2e2f9c9f7189
Revises: c08b529747ef
Create Date: 2025-12-13 16:02:45.596058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e2f9c9f7189'
down_revision: Union[str, Sequence[str], None] = 'c08b529747ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('display_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'display_name')
    # ### end Alembic commands ###
